### ISSUE TITLE
User can view products.

### ISSUE THREAD

**Issue by Kiptong** [Kiptong/Foodie-Swag#1]
# Motivation 
Allow user to view products available for purchase.

# Implementation 
- [x] Create and link index.html, styles.css, and main.js files 
- [x] Create and label containers with corresponding Bootstrap3 classes
- [x] Fill Containers with product photos and titles
![Issue #1 Wireframe](https://occs.mybalsamiq.com/mockups/5913011.png?key=e2cca4892e20eb5fb2ea8746155d5fa697d3b862)

**Comment by ronperris** [comment]
![Wireframe](https://occs.mybalsamiq.com/mockups/5909856.png?key=aef0224fe4061a47eab85d6cd41b4fd3ecbe08b7)
